### ISSUE TITLE
Destination addresses do not match. It is 32. It should be 1.

### ISSUE THREAD

**Issue by rahultalangkar** [Gurux/gurux.dlms.java#10]
Getting Exception **Destination addresses do not match. It is 32. It should be 1.**

File: gurux.dlms.java/gurux.dlms.client.example.java/src/gurux/dlms/client/GXCommunicate.java
Line No.: 224

Using Genus Meter & ind.obx as manufacturer settings file
Authentication: None

**Comment by gurux01** [comment]
Hi, 
Create new template for Genus get.obx and change server address to 1.
That will solve the problem.

**Comment by rahultalangkar** [comment]
@gurux01 
Thanks for quick reply,
I observed that there are several ready templates in ManufacturerSettings, I was quite confused which one to use , but finally concluded with ind.obx.
But now if I create get.obx what will be the other settings except Server address to 1. e.g. ObisCode, ClientAddress, Authentication, etc.

or should I use any other template as base template with Server address changed to 1.

**Comment by gurux01** [comment]
Hi,

You can take Indian standard as a template and modify it.
It's a big problem that  different manufacturers are using different settings. :-(
For this reason we start to use manufacturer settings.

BR,

Mikko

**Comment by rahultalangkar** [comment]
@gurux01 
if I use get.obx with ind.obx template , programs throws an exception **java.lang.RuntimeException: Invalid manufacturer.**

may be its no able to recognize the manufacturer.

If possible, can you help me out in understanding or converting all replies that we get from meter to human readable format.

**Comment by gurux01** [comment]
Hi,

Reason for this is that your Genus meter returns something else than "get" as flag id. When you made connection you will send ?/!. What meter returns?

We are just making end tests for xml translator. Wait few days.

BR,

Mikko
