### ISSUE TITLE
Scaler with Demand Register or Extended Register in Generic Profile

### ISSUE THREAD

**Issue by angelfmarcos** [Gurux/gurux.dlms.java#19]
It seems than in Demand Register (class_id: 5) or Extended Register (class_id: 4) scaler is not applied.

In GXDLMSProfileGeneric.setBuffer() appears that only GXDLMSRegister instances are taken into account to apply scaler.

**Comment by gurux01** [comment]
Hi,

GXDLMSExtendedRegister is derived from GXDLMSRegister so that is handled, but 
GXDLMSDemandRegister is not. We have fixed this and we are testing it now. New version is available today.

**Comment by gurux01** [comment]
Hi,

Version 1.4.11 is available where we have added support for GXDLMSDemandRegister.
