### ISSUE TITLE
Constructor of GXDLMSRegister not working properly

### ISSUE THREAD

**Issue by dhufnagel** [Gurux/gurux.dlms.java#2]
The constructor 

  public GXDLMSRegister(String ln, int sn)

does not set the shortname. It calls the constructor 

  public GXDLMSRegister(ObjectType type, String ln, int sn)

with paramter sn set to 0. Seems to be copied from constructor without sn-parameter.

**Comment by gurux01** [comment]
Hi,

Thank you for let us know from this. We have fixed this issue.
New version is in GitHub.

BR,

Mikko
