### ISSUE TITLE
HTTP error 406 code while trying to update manufacture setting 

### ISSUE THREAD

**Issue by hernaneche** [Gurux/gurux.dlms.java#24]
This is the error: 

> java.lang.RuntimeException:
> Server returned HTTP response code: 406 for URL: http://www.gurux.fi/obis/files.xml
> 	at gurux.dlms.manufacturersettings.GXManufacturerCollection.updateManufactureSettings(GXManufacturerCollection.java:242) ~[classes/:na]

**Comment by gurux01** [comment]
Hi,

This is fixed for our server. Firewall was updated and it cause some problems.
