### ISSUE TITLE
Gurux library with android to read meter reading using optical probe

### ISSUE THREAD

**Issue by achinverma** [Gurux/gurux.dlms.java#3]
hi, i have to read meter reading in android and i have found gurux library in java https://github.com/Gurux/gurux.dlms.java
but i want to use this library in android to read meter i will post my meter image , and i also have optical probe which get connected to my meter , basically, i want to make a simple app which is used to read meter reading .
as i have told you that i have optical probe i will connect this to my android phone using OTG support and other end is connected to meter as you can see in picture, so please you guide me how to read this reading ?
![img_20151017_101757983](https://cloud.githubusercontent.com/assets/2811593/10557102/a87198b4-74ba-11e5-9d62-8e1dfbdeddd2.jpg)

optical probe 
![images](https://cloud.githubusercontent.com/assets/2811593/10557103/b2bb0da0-74ba-11e5-83d3-960697b72281.jpg)

  
![iec-energy-meters-usb-cable-iec-62056-21-standard-infrared-optical-probe](https://cloud.githubusercontent.com/assets/2811593/10557105/b604db80-74ba-11e5-85e4-cf5ea5a53e78.jpg)

**Comment by gurux01** [comment]
Hi,

I have answer for this question on Gurux Forum.

BR,

Mikko

**Comment by achinverma** [comment]
@gurux01 , please can you send me the link . i have searched it but could not find it.
