### ISSUE TITLE
A folder missing?

### ISSUE THREAD

**Issue by merismeris** [Gurux/gurux.dlms.java#4]
Dear developers,
I downloaded and build the project gurux.dlms.java and my IDE gives some errors because it doesnt find the folder gurux.dlms.manufacturersettings. I didnt find this folder in the github repository either. Could you upload this missing folder, please? Thanks a lot for your fantastic work!

**Comment by gurux01** [comment]
Hi,

You are right. We updated manufacturersetting. You can get latest sources.
BTW: Use Gurux Forum if you have problems. 
BR,

Mikko
