### ISSUE TITLE
Wrong enum value for "sort_method" attribute

### ISSUE THREAD

**Issue by mnehad** [Gurux/gurux.dlms.java#6]
Hi,

I'm using "gurux.dlms.java" library and I have noticed in gurux.dlms.objects.enums.SortMethod enum that values are not correct according to COSEM Blue book (attribute sort_method of Profile generic object :
* enum SortMethod 
> FIFO(0),
> LIFO(1),
> LARGEST(2),
> SMALLEST(3),
> NEAREST_TO_ZERO(4),
> FAREST_FROM_ZERO(5);

* Blue book :
> (1) fifo (first in first out),
> (2) lifo (last in first out),
> (3) largest,
> (4) smallest,
> (5) nearest_to_zero,
> (6) farest_from_zero

Thanks
Mansour

**Comment by gurux01** [comment]
Hi,

You was right. This is fixed.
